# src: https://github.com/dineshsonachalam/repo-using-markdown-autodocs/blob/main/.github/workflows/markdown-autodocs.yml
# Sahil: I updated so it runs on push via `on: [push]`
name: markdown-autodocs

on: [push]

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.7
          with:
            output_file_paths: '[./README.md]'
            # output_file_paths: '[./README.md,./docs/example.md]'