# src: https://github.com/jaames/iro.js/blob/master/.github/workflows/markdown-autodocs.yml
#     - Sahil: I updated the version of markdown-autodocs from `1.0.2` (used in above file) to `1.0.7` (latest).

name: markdown-autodocs

on:
  push:
    branches:    
      - '**'        # matches every branch

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.7